{ pkgs, lib, config, ... }:

{

  # Containers
  virtualisation.oci-containers.containers."doco-cd" = {
    image = "ghcr.io/kimdre/doco-cd:0.53.0";
    environment = {
      "HTTP_PORT" = "99";
      "POLL_CONFIG" = "- url: https://github.com/pcs3rd/stickpile_compose-config.git  # This is the repository to poll
    reference: dev  # Optional: specify the branch or tag to poll, defaults to 'main'
    interval: 60  # Optional: specify the interval in seconds to poll the repository, defaults to 180 seconds (3 minutes)
    target: \"\"  # Optional: use to target a specific deployment config file, e.g., \"test\" -> .doco-cd.test.yaml
  ";
      "SOPS_AGE_KEY_FILE" = "/run/secrets/sops_age_key";
      "TZ" = "America/New_York";
    };
    volumes = [
      "/persist/prod/base/doco-cd:/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "9120:9120/tcp"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.doco.entrypoints" = "websecure";
      "traefik.http.routers.doco.rule" = "Host(`doco-cd.webhook.stickpile.net`)";
      "traefik.http.routers.doco.tls.certresolver" = "httpsResolve";
      "traefik.http.services.doco.loadbalancer.server.port" = "99";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"wget\", \"--no-verbose\", \"--tries=1\", \"--spider\", \"http://localhost:99/v1/health\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=15s"
      "--health-timeout=5s"
      "--network-alias=doco-cd"
      "--network=traefik_backbone"
    ];
  };
  systemd.services."podman-dummy-doco-cd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-dummy-root.target"
    ];
    wantedBy = [
      "podman-compose-dummy-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-dummy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}